# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=254, verbose_name='Nombre del picto')),
                ('descripcion', models.TextField(blank=True, help_text='descripción del picto')),
                ('picto', models.ForeignKey(blank=True, help_text='Picto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
